name: Hello World Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu_latest
    steps:
      - uses: actions/checkout@v2
      - name: hello World
        run: echo "Hello World"
        shell: bash

  goodbye:
    runs-on: ubuntu_latest
    steps:
      - name: goodbye world
        run: echo "GoodBye World" 
        shell: bash
                        
